### ISSUE TITLE
Invoke Error

### ISSUE THREAD

**Issue by dspv** [kabisa/terraform-aws-logdna#6]
Everything deployed correctly, but I'm having issue when invoking the Lambda

```
START RequestId: 4f7765e8-2921-455d-bb15-19fa29f6921a Version: $LATEST
2022-03-01T12:19:05.666Z	4f7765e8-2921-455d-bb15-19fa29f6921a	ERROR	Invoke Error 	{"errorType":"TypeError","errorMessage":"Cannot read property 'data' of undefined","stack":["TypeError: Cannot read property 'data' of undefined","    at parseEvent (/var/task/index.js:41:64)","    at Runtime.exports.handler (/var/task/index.js:135:33)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
END RequestId: 4f7765e8-2921-455d-bb15-19fa29f6921a
REPORT RequestId: 4f7765e8-2921-455d-bb15-19fa29f6921a	Duration: 2.81 ms	Billed Duration: 3 ms	Memory Size: 128 MB	Max Memory Used: 78 MB	
```

Any advice how to fix?

**Comment by jwavoet** [comment]
Hi @dspv,

Which release are you using? Could you try the [latest](https://github.com/cloud-legends/terraform-aws-logdna/releases/tag/v2.2.0) and let me know if that solves your issue?
